# Generated by Django 3.1.1 on 2020-09-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_tags',
            field=models.CharField(default=None, max_length=1500),
        ),
    ]
