# Generated by Django 3.1.1 on 2020-09-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_tags',
            new_name='tags',
        ),
    ]
