# Generated by Django 3.1.1 on 2020-09-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_account_user_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_tags',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
