# Generated by Django 3.1.1 on 2020-09-29 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200929_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='apology',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apology',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
