# Generated by Django 3.1.1 on 2020-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200929_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apology',
            name='post_text',
            field=models.TextField(),
        ),
    ]
