# Generated by Django 3.1.1 on 2020-10-01 21:56

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('main_app', '0006_auto_20200930_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apology',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
